### ISSUE TITLE
请教为什么需要在 unpad 之后清除 \a ？

### ISSUE THREAD

**Issue by imyelo** [xlstudio/wxbizdatacrypt#1]
https://github.com/xlstudio/wxbizdatacrypt/blob/56d06ae4328bcfc972647c5565c4d835dd79ba32/wxbizdatacrypt.go#L71

是有什么特殊的原因吗？ :thinking:

**Comment by Xiphin** [comment]
这是历史遗留下来的。在原来项目实践中遇到的，有时候解密后的 json 字符串后面会多出一个 \a 来了，不过不多见，我猜想应该是语言差异造成的

**Comment by imyelo** [comment]
get. 谢谢啦 :+1:
