### ISSUE TITLE
调用该包出现 invalid character 'b' looking for beginning of value

### ISSUE THREAD

**Issue by kuzicala** [xlstudio/wxbizdatacrypt#2]
错误返回如下 
{code: -41003, error: "invalid character 'î' looking for beginning of value"}
不是每次都出现，是出现一次，然后又可以获取用户信息了，

**Comment by Xiphin** [comment]
给个出现此类情况的加密数据看一下

**Comment by Xiphin** [comment]
我修改了一下。你更新一下代码再试试

**Comment by kuzicala** [comment]
更新了下包 还是出现
{code: -41003, error: "invalid character '÷' looking for beginning of value"}
encryptedData:v0tSz36CblTjxf+L8yH1oUCCggi/83WQ9/ZSZz2uiPdQNTOKL6wywRV+elZcozsJwqdDemIoB8wLSdMEkn1p0ylbtnZ8nIiSp5oToAhZVrRT6tCeI4huJ1+wkn3jjZNLXhD936msXWnBew+8riZRweId74gcQAKCI1VwqNN1UjX6/qY0H1a4O0FJpNFWeLwHz5hXaL5wS83sRwZWCw+AFFUZVtA5SerZawfuInFbF9wntUmpq8Jsmg4qRWTlfCOAfvAwLRAdZ2mMs0mcGWpIPe+8BvQfT+CSYIfLGuOsgvFngD5lOlB8GmKJMTvVNHHoWn51Lgu4JU6oSBSOJ55AdMjZZx7Ap2MY4bpH+H0+6lapzAfWNsmSd8ODEdOp0bc0wtUvDRwqDT2gNYExX8Yfhe+vMDC0/QzHFqtAC9oOh3iyT6z4N0b4r2mmXATfkWlYijUTaoy1kK2cj3FODmCXY9JBNf4ZbYBdcMVE0E9GVhKGVc2RH8oUkPDyGCPrhzMIiZIC5ddsVAVpEw70XQeYnnvmg5Yyt9ueUMMgsKrsSZI=

**Comment by kuzicala** [comment]
出个这个问题的情况和刚才 我描述的一样，再一次请求 解密时候 出现 错误，前台重新 click button获取用户信息后，在次解密 就ok了~~

**Comment by Xiphin** [comment]
再更新一下，试试

**Comment by kuzicala** [comment]
{code: -41003, error: "invalid character 'O' looking for beginning of value"}

A1zTlwEvrWdoNBHAEKIafNVUGEC31Urjb+WtIsI7IZ+8gdYMzNTxRP5y0cLMaPztQNit9CglIXV0wUL6UUDNJO3RapZrakS2S1LSt+SC9OneR2Gglm95VyGj0ysERcR+sM6s8J1kiYbkFGio7sE15B9+3koAvEtUXwhbWu5zKHl1b25/fxqFa0xKVs54bIcm60ArTUGluxwvfUEqXmG5doFXuh+o02opjBCs7TgARLiDSVK76z9AuMm9zxSuCG41kk6cJAdfKiOHYB3BUpjyFRl2K5YyOr356+WuoKpOI39iUt5C+wi3sb4R12aeJvUnqBkRgPwNMh098egD4xqOK8YdUQnjlhKcgZMkXSKjTFVPWIATYaYWdpDuLr8KXqOzb1T3aaMBPEIRpwMKC2U6dDvTYi6WIBhVP4l4o/OwDDoulj6JBVFlrWigR7w+fGlWvRlnFM7EbNIUOfdajs6AddoyJHi+KWXkqSz+AvmKSzc8SqvyFxvzMvqSJW816Nii6IhLQaBU9SWG/AWW+P0u/NZFV54yyvUTKvxoXgd3Fqc=

**Comment by Xiphin** [comment]
更新一下，再贴一下错误

**Comment by kuzicala** [comment]
{code: -41003, error: "invalid character '\x16' looking for beginning of value"}

OITJqcj7kWnZiGHaRWwBDPOCRtssqFzhxpmXcLcwE3HHRprcYDvkdzBa3fhxLgqiV3gG+1vsVxhg4qQBUqyGeAN5hb8ETxfxFy0X9bAHexliKOvsiPG1y+ORff+XI3n3DcfN7o7TvvRKW67p/ib4tXWxlin50hGnOr2SAIm4+nDcX2F7HVaK6E/TDG+q6QHPRFTyviWWWpMLXkkvrN8EGT+HRmOGBzM8vwhYNgok+O/pbJzYWkCoW+bsumxarSJHlARoatndAMz2m9NE+CaxmRN71EF4Hv19j0/soEvryS+1v74XrlfMrEDIzjonj72VWf8yuM0MTtib7NkLeiWP2q8NeIc0UigV26xqw6TOCKzkPmPWRp8FuL8hJ83Ki85Lk1ptPDaYlECcFczMaBAwjqjaSgMCvksmvak8mL9PekcuE/YMRR1GJ8MSZ6NKW3u/B3rZTbS1feSbXwui2JTUxXgN07P3hLCCtHT7gnYb+3BaQo/h8lEnIb70MLm6OJybqNx6lClFoxyA7zKTmet0f9P1emejlX1khnnOX0HGekY=

**Comment by kuzicala** [comment]
有时成功 有时失败
 {code: -41003, error: "invalid character '\u0082' looking for beginning of value"}

**Comment by Xiphin** [comment]
报错位置：
https://github.com/xlstudio/wxbizdatacrypt/blob/master/wxbizdatacrypt.go#L63-L66
```
	aesBlock, err := aes.NewCipher(aesKey)
	if err != nil {
		return nil, showError{errorCode["IllegalBuffer"], err}
	}
```
怀疑可能是aesKey的值有问题，有点想不明白。加一下Q: 2019809069 聊一下

**Comment by Xiphin** [comment]
也就是说 你每一次的 session_key 可能不一样 有时有问题

**Comment by Xiphin** [comment]
传 session_key 的时候，注意一下，看是不有额外的字符，比如空格什么的

**Comment by chyroc** [comment]
这个问题好像是：encrypteData, sessionKey不匹配

我的解决方案是让客户端用新的code和encrypteData重试

**Comment by Xiphin** [comment]
> 这个问题好像是：encrypteData, sessionKey不匹配
> 
> 我的解决方案是让客户端用新的code和encrypteData重试

是的
