### ISSUE TITLE
解密偶发报错

### ISSUE THREAD

**Issue by CNbluer** [xlstudio/wxbizdatacrypt#4]
偶发性的报错 频率还不抵 我和前端都很懵逼 不知道为什么 {code: -41004, error: "illegal base64 data at input byte 8"}

**Comment by Xiphin** [comment]
偶尔性的报错：你可以先记录日志 再分析主要是哪些解密不了，分析一下字符串的规律

**Comment by CNbluer** [comment]
按照您的思路 我发现这些字符串都有空格 于是我去了空格 结果出现这种报错 invalid character '¼' looking for beginning of value

**Comment by Xiphin** [comment]
用QQ么，可以加我一下：2019809069(微信同号)，帮你看看

**Comment by Xiphin** [comment]
或者 提供一个类似的完整字符串给我

**Comment by cute-angelia** [comment]
{code: -41005, error: "invalid character 'Ú' looking for beginning of value"}
{code: -41005, error: "invalid character 'þ' looking for beginning of value"}


会否是 json 解析的库有问题

**Comment by Xiphin** [comment]
> {code: -41005, error: "invalid character 'Ú' looking for beginning of value"}
> {code: -41005, error: "invalid character 'þ' looking for beginning of value"}
> 
> 会否是 json 解析的库有问题

json 用的是 golang 的内置库

**Comment by cute-angelia** [comment]
wechat -41005 error: "invalid character

频率越来越高了， 解密， 现在第一次基本都是失败

**Comment by Xiphin** [comment]
> wechat -41005 error: "invalid character
> 
> 频率越来越高了， 解密， 现在第一次基本都是失败

解密前最好记录一下入参的加密数据 ，然后你试着用官方提供的其他语言解密一下，看能不能解开，如能解开就说明是我的库有问题，及时反馈给我。如也不能解开的话就有可能是加密数据出现了丢失或格式出现了问题。

**Comment by cute-angelia** [comment]
> > wechat -41005 error: "invalid character
> > 频率越来越高了， 解密， 现在第一次基本都是失败
> 
> 解密前最好记录一下入参的加密数据 ，然后你试着用官方提供的其他语言解密一下，看能不能解开，如能解开就说明是我的库有问题，及时反馈给我。如也不能解开的话就有可能是加密数据出现了丢失或格式出现了问题。

好的

**Comment by cute-angelia** [comment]
> > wechat -41005 error: "invalid character
> > 频率越来越高了， 解密， 现在第一次基本都是失败
> 
> 解密前最好记录一下入参的加密数据 ，然后你试着用官方提供的其他语言解密一下，看能不能解开，如能解开就说明是我的库有问题，及时反馈给我。如也不能解开的话就有可能是加密数据出现了丢失或格式出现了问题。

经过数据测试， 其他语言的版本也解不开




经过几小时测试，最终定位到问题

客户端先拿`encryptedData`，`iv`， 再去拿 `code`， 然后交给服务端， 这个数据先后顺序直接影响了解密结果


正确做法是： 客户端先拿 `code`，再去拿 `encryptedData`，`iv`

**Comment by Xiphin** [comment]
> > > wechat -41005 error: "invalid character
> > > 频率越来越高了， 解密， 现在第一次基本都是失败
> > 
> > 
> > 解密前最好记录一下入参的加密数据 ，然后你试着用官方提供的其他语言解密一下，看能不能解开，如能解开就说明是我的库有问题，及时反馈给我。如也不能解开的话就有可能是加密数据出现了丢失或格式出现了问题。
> 
> 经过数据测试， 其他语言的版本也解不开
> 
> 经过几小时测试，最终定位到问题
> 
> 客户端先拿`encryptedData`，`iv`， 再去拿 `code`， 然后交给服务端， 这个数据先后顺序直接影响了解密结果
> 
> 正确做法是： 客户端先拿 `code`，再去拿 `encryptedData`，`iv`

:+1: 谢谢你的经验分享，很有参考意义。
