### ISSUE TITLE
Issue 5

### ISSUE THREAD

**Issue by samkk** [xlstudio/wxbizdatacrypt#5]
{code: -41005, error: "invalid character '\u008d' after top-level value"}
{code: -41005, error: "invalid character 'Ô' looking for beginning of value"}

请求4、5次可能就会出错一次
打印出来的
�Y�@���N����꜅�,��5�
g����L�X1m�Y]�QO�|��P���-��L���rt���X<o /��|N�����`�����Z��6��X��>�$���Ԣ<y���b��C�Ԟ����

**Comment by Xiphin** [comment]
I'm so sorry!
方便的话加一下我 QQ：2019809069
提供一下样本数据
